services:
  - type: web
    name: drivenpass-api
    env: node
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npx prisma db seed && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: drivenpass-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CRYPTR_SECRET
        generateValue: true
      - key: PORT
        value: 10000

databases:
  - name: drivenpass-db
    databaseName: drivenpass
    user: drivenpass
